export type PricingServiceGuideSpec = {
  slug: string;
  title: string;
  routeLabel: string;
  problem: string;
  tableLabel: string;
  ironcladPrice: string;
  austinRange: string;
  askWhyOver: string;
  detailHeading?: string;
};

export const PRICING_SERVICE_GUIDE_SPECS: PricingServiceGuideSpec[] = [
  {
    slug: "drain-cleaning-cost-austin",
    title: "Drain Cleaning Cost in Austin",
    routeLabel: "Drain Cleaning Cost",
    problem: "Clogged sink or shower drain",
    tableLabel: "Drain cleaning (single fixture)",
    ironcladPrice: "$175",
    austinRange: "$125-$300",
    askWhyOver: "Over $350",
    detailHeading: "Drain Cleaning (Single Fixture)",
  },
  {
    slug: "mainline-drain-cleaning-cost-austin",
    title: "Mainline Drain Cleaning Cost in Austin",
    routeLabel: "Mainline Drain Cleaning Cost",
    problem: "Clogged main sewer line",
    tableLabel: "Mainline drain cleaning",
    ironcladPrice: "$300",
    austinRange: "$200-$450",
    askWhyOver: "Over $500",
  },
  {
    slug: "toilet-internal-repair-cost-austin",
    title: "Toilet Internal Repair Cost in Austin",
    routeLabel: "Toilet Internal Repair Cost",
    problem: "Toilet won't stop running",
    tableLabel: "Toilet internal repair",
    ironcladPrice: "$150",
    austinRange: "$100-$250",
    askWhyOver: "Over $300",
    detailHeading: "Toilet Internal Repair",
  },
  {
    slug: "toilet-pull-and-reseat-cost-austin",
    title: "Toilet Pull and Reseat Cost in Austin",
    routeLabel: "Toilet Pull and Reseat Cost",
    problem: "Toilet rocking / leaking at base",
    tableLabel: "Toilet pull and reseat",
    ironcladPrice: "$225",
    austinRange: "$150-$325",
    askWhyOver: "Over $400",
  },
  {
    slug: "toilet-replacement-cost-austin",
    title: "Toilet Replacement Cost in Austin",
    routeLabel: "Toilet Replacement Cost",
    problem: "Need a new toilet installed",
    tableLabel: "Toilet replacement",
    ironcladPrice: "$450",
    austinRange: "$300-$700",
    askWhyOver: "Over $800",
  },
  {
    slug: "faucet-repair-cost-austin",
    title: "Faucet Repair Cost in Austin",
    routeLabel: "Faucet Repair Cost",
    problem: "Faucet dripping or leaking",
    tableLabel: "Faucet repair (cartridge swap)",
    ironcladPrice: "$175",
    austinRange: "$125-$275",
    askWhyOver: "Over $325",
  },
  {
    slug: "faucet-replacement-cost-austin",
    title: "Faucet Replacement Cost in Austin",
    routeLabel: "Faucet Replacement Cost",
    problem: "Need a new faucet installed",
    tableLabel: "Faucet replacement (standard)",
    ironcladPrice: "$375",
    austinRange: "$250-$550",
    askWhyOver: "Over $650",
    detailHeading: "Faucet Replacement (Standard Kitchen or Bath)",
  },
  {
    slug: "water-heater-replacement-cost-austin",
    title: "Water Heater Replacement Cost in Austin",
    routeLabel: "Water Heater Replacement Cost",
    problem: "No hot water / heater leaking",
    tableLabel: "Water heater replacement (50-gal gas, garage)",
    ironcladPrice: "$2,200",
    austinRange: "$1,400-$3,500",
    askWhyOver: "Over $4,000",
    detailHeading: "Water Heater Replacement (50-Gallon Gas Tank, Garage)",
  },
  {
    slug: "tankless-water-heater-install-cost-austin",
    title: "Tankless Water Heater Install Cost in Austin",
    routeLabel: "Tankless Water Heater Install Cost",
    problem: "Want to switch to tankless",
    tableLabel: "Tankless install (full conversion)",
    ironcladPrice: "$4,500",
    austinRange: "$3,000-$6,500",
    askWhyOver: "Over $7,000",
    detailHeading: "Tankless Water Heater (Full Conversion)",
  },
  {
    slug: "garbage-disposal-replacement-cost-austin",
    title: "Garbage Disposal Replacement Cost in Austin",
    routeLabel: "Garbage Disposal Replacement Cost",
    problem: "Garbage disposal broken",
    tableLabel: "Disposal replacement (1/2 HP)",
    ironcladPrice: "$350",
    austinRange: "$225-$500",
    askWhyOver: "Over $600",
    detailHeading: "Garbage Disposal Replacement",
  },
  {
    slug: "sewer-camera-inspection-cost-austin",
    title: "Sewer Camera Inspection Cost in Austin",
    routeLabel: "Sewer Camera Inspection Cost",
    problem: "Slow drains everywhere",
    tableLabel: "Sewer camera inspection",
    ironcladPrice: "$275",
    austinRange: "$150-$400",
    askWhyOver: "Over $500",
    detailHeading: "Sewer Camera Inspection",
  },
  {
    slug: "sewer-repair-cost-austin",
    title: "Sewer Repair Cost in Austin",
    routeLabel: "Sewer Repair Cost",
    problem: "Sewer line needs repair",
    tableLabel: "Sewer spot repair",
    ironcladPrice: "$2,000",
    austinRange: "$1,000-$3,500",
    askWhyOver: "Over $4,000 without camera evidence",
  },
  {
    slug: "leak-detection-cost-austin",
    title: "Leak Detection Cost in Austin",
    routeLabel: "Leak Detection Cost",
    problem: "Water bill spiked / suspect leak",
    tableLabel: "Leak detection",
    ironcladPrice: "$350",
    austinRange: "$200-$500",
    askWhyOver: "Over $600",
    detailHeading: "Leak Detection",
  },
  {
    slug: "slab-leak-spot-repair-cost-austin",
    title: "Slab Leak Spot Repair Cost in Austin",
    routeLabel: "Slab Leak Spot Repair Cost",
    problem: "Leak under slab foundation",
    tableLabel: "Slab leak spot repair",
    ironcladPrice: "$2,000",
    austinRange: "$1,200-$3,500",
    askWhyOver: "Over $4,000 without showing you evidence",
  },
  {
    slug: "hydro-jetting-cost-austin",
    title: "Hydro Jetting Cost in Austin",
    routeLabel: "Hydro Jetting Cost",
    problem: "Pipes need high-pressure cleaning",
    tableLabel: "Hydro jetting",
    ironcladPrice: "$450",
    austinRange: "$300-$700",
    askWhyOver: "Over $800",
    detailHeading: "Hydro Jetting",
  },
  {
    slug: "gas-line-installation-cost-austin",
    title: "Gas Line Installation Cost in Austin",
    routeLabel: "Gas Line Installation Cost",
    problem: "Gas line for new appliance",
    tableLabel: "Gas line run (short, same room)",
    ironcladPrice: "$400",
    austinRange: "$250-$600",
    askWhyOver: "Over $750",
    detailHeading: "Gas Line (Short Run, Same Room)",
  },
  {
    slug: "water-softener-installation-cost-austin",
    title: "Water Softener Installation Cost in Austin",
    routeLabel: "Water Softener Installation Cost",
    problem: "Hard water destroying fixtures",
    tableLabel: "Whole-house water softener",
    ironcladPrice: "$2,500",
    austinRange: "$1,500-$4,000",
    askWhyOver: "Over $5,000",
    detailHeading: "Whole-House Water Softener",
  },
  {
    slug: "hose-bib-replacement-cost-austin",
    title: "Hose Bib Replacement Cost in Austin",
    routeLabel: "Hose Bib Replacement Cost",
    problem: "Outdoor faucet broken",
    tableLabel: "Hose bib replacement",
    ironcladPrice: "$200",
    austinRange: "$125-$300",
    askWhyOver: "Over $375",
  },
  {
    slug: "prv-replacement-cost-austin",
    title: "PRV Replacement Cost in Austin",
    routeLabel: "PRV Replacement Cost",
    problem: "Water pressure issues",
    tableLabel: "PRV replacement",
    ironcladPrice: "$400",
    austinRange: "$250-$550",
    askWhyOver: "Over $650",
  },
  {
    slug: "emergency-plumber-cost-austin",
    title: "Emergency Plumber Cost in Austin",
    routeLabel: "Emergency Plumber Cost",
    problem: "Emergency plumber now",
    tableLabel: "After-hours dispatch + repair",
    ironcladPrice: "$200 dispatch + repair",
    austinRange: "$150-$400 dispatch + repair",
    askWhyOver: "Dispatch over $500 before any work",
    detailHeading: "Emergency Service Call",
  },
  {
    slug: "water-heater-repair-cost-austin",
    title: "Water Heater Repair Cost in Austin",
    routeLabel: "Water Heater Repair Cost",
    problem: "Water heater not working but not leaking",
    tableLabel: "Water heater repair (element, thermocouple, pilot)",
    ironcladPrice: "$250",
    austinRange: "$150-$400",
    askWhyOver: "Over $450",
    detailHeading: "Water Heater Repair (Not Replacement)",
  },
  {
    slug: "shower-valve-replacement-cost-austin",
    title: "Shower Valve Replacement Cost in Austin",
    routeLabel: "Shower Valve Replacement Cost",
    problem: "Shower won't turn off / won't mix hot and cold",
    tableLabel: "Shower valve replacement",
    ironcladPrice: "$400",
    austinRange: "$275-$600",
    askWhyOver: "Over $700",
    detailHeading: "Shower Valve Replacement",
  },
  {
    slug: "repipe-cost-austin",
    title: "Repipe Cost in Austin",
    routeLabel: "Repipe Cost",
    problem: "Pipes are old and corroded throughout house",
    tableLabel: "Whole-house repipe (copper or PEX)",
    ironcladPrice: "$8,500",
    austinRange: "$5,000-$15,000",
    askWhyOver: "Over $18,000 without detailed scope",
    detailHeading: "Whole-House Repipe",
  },
  {
    slug: "trenchless-sewer-lining-cost-austin",
    title: "Trenchless Sewer Lining Cost in Austin",
    routeLabel: "Trenchless Sewer Lining Cost",
    problem: "Sewer line damaged but don't want to dig up yard",
    tableLabel: "Trenchless sewer lining (CIPP)",
    ironcladPrice: "$5,500",
    austinRange: "$3,500-$9,000",
    askWhyOver: "Over $10,000 without camera evidence",
    detailHeading: "Trenchless Sewer Lining (CIPP)",
  },
  {
    slug: "main-water-line-repair-cost-austin",
    title: "Main Water Line Repair Cost in Austin",
    routeLabel: "Main Water Line Repair Cost",
    problem: "Water line from meter to house is leaking",
    tableLabel: "Main water line repair/replacement",
    ironcladPrice: "$2,500",
    austinRange: "$1,500-$5,000",
    askWhyOver: "Over $6,000",
    detailHeading: "Main Water Line Repair / Replacement",
  },
  {
    slug: "dishwasher-installation-cost-austin",
    title: "Dishwasher Installation Cost in Austin",
    routeLabel: "Dishwasher Installation Cost",
    problem: "Need a dishwasher hooked up",
    tableLabel: "Dishwasher installation (with existing connections)",
    ironcladPrice: "$250",
    austinRange: "$150-$400",
    askWhyOver: "Over $500",
    detailHeading: "Dishwasher Installation",
  },
  {
    slug: "sink-installation-cost-austin",
    title: "Sink Installation Cost in Austin",
    routeLabel: "Sink Installation Cost",
    problem: "Sink or vanity needs replacing",
    tableLabel: "Sink installation (kitchen or bath)",
    ironcladPrice: "$450",
    austinRange: "$300-$650",
    askWhyOver: "Over $750",
    detailHeading: "Sink Installation (Kitchen or Bathroom)",
  },
  {
    slug: "shutoff-valve-replacement-cost-austin",
    title: "Shutoff Valve Replacement Cost in Austin",
    routeLabel: "Shutoff Valve Replacement Cost",
    problem: "Shutoff valve under sink or behind toilet is stuck/leaking",
    tableLabel: "Shutoff valve replacement (single)",
    ironcladPrice: "$175",
    austinRange: "$100-$275",
    askWhyOver: "Over $325",
    detailHeading: "Shutoff Valve Replacement (Single Fixture)",
  },
  {
    slug: "recirculation-pump-installation-cost-austin",
    title: "Recirculation Pump Installation Cost in Austin",
    routeLabel: "Recirculation Pump Installation Cost",
    problem: "Want hot water faster at distant faucets",
    tableLabel: "Recirculation pump installation",
    ironcladPrice: "$650",
    austinRange: "$400-$900",
    askWhyOver: "Over $1,100",
    detailHeading: "Recirculation Pump Installation",
  },
  {
    slug: "washing-machine-valve-box-replacement-cost-austin",
    title: "Washing Machine Valve Box Replacement Cost in Austin",
    routeLabel: "Washing Machine Valve Box Replacement Cost",
    problem: "Washing machine supply valves are old/leaking",
    tableLabel: "Washing machine valve box replacement",
    ironcladPrice: "$275",
    austinRange: "$175-$400",
    askWhyOver: "Over $500",
    detailHeading: "Washing Machine Valve Box Replacement",
  },
  {
    slug: "pipe-leak-repair-cost-austin",
    title: "Pipe Leak Repair Cost in Austin",
    routeLabel: "Pipe Leak Repair Cost",
    problem: "Pipe is leaking (visible, not under slab)",
    tableLabel: "Pipe leak repair (accessible)",
    ironcladPrice: "$275",
    austinRange: "$150-$450",
    askWhyOver: "Over $500",
    detailHeading: "Pipe Leak Repair (Accessible / Visible)",
  },
  {
    slug: "tub-shower-trim-replacement-cost-austin",
    title: "Tub and Shower Trim Replacement Cost in Austin",
    routeLabel: "Tub and Shower Trim Replacement Cost",
    problem: "Bathtub or shower faucet/spout is old or broken",
    tableLabel: "Tub/shower trim and spout replacement",
    ironcladPrice: "$350",
    austinRange: "$225-$500",
    askWhyOver: "Over $600",
    detailHeading: "Bathtub / Shower Trim and Spout Replacement",
  },
  {
    slug: "water-heater-flush-cost-austin",
    title: "Water Heater Flush Cost in Austin",
    routeLabel: "Water Heater Flush Cost",
    problem: "Water heater needs maintenance",
    tableLabel: "Water heater flush and inspection",
    ironcladPrice: "$150",
    austinRange: "$80-$250",
    askWhyOver: "Over $300",
    detailHeading: "Water Heater Flush and Inspection",
  },
  {
    slug: "reverse-osmosis-installation-cost-austin",
    title: "Reverse Osmosis Installation Cost in Austin",
    routeLabel: "Reverse Osmosis Installation Cost",
    problem: "Want filtered drinking water at kitchen sink",
    tableLabel: "Reverse osmosis system (under-sink)",
    ironcladPrice: "$550",
    austinRange: "$350-$800",
    askWhyOver: "Over $950",
    detailHeading: "Reverse Osmosis System (Under-Sink)",
  },
  {
    slug: "sump-pump-installation-cost-austin",
    title: "Sump Pump Installation Cost in Austin",
    routeLabel: "Sump Pump Installation Cost",
    problem: "Basement or crawlspace floods when it rains",
    tableLabel: "Sump pump installation",
    ironcladPrice: "$800",
    austinRange: "$500-$1,400",
    askWhyOver: "Over $1,600",
    detailHeading: "Sump Pump Installation",
  },
  {
    slug: "backflow-preventer-cost-austin",
    title: "Backflow Preventer Cost in Austin",
    routeLabel: "Backflow Preventer Cost",
    problem: "Backflow device needs testing or replacement",
    tableLabel: "Backflow preventer test / replacement",
    ironcladPrice: "$175 test / $450 replace",
    austinRange: "$75-$250 test / $300-$700 replace",
    askWhyOver: "Test over $300 / Replace over $800",
    detailHeading: "Backflow Preventer Testing / Replacement",
  },
  {
    slug: "sewer-cleanout-installation-cost-austin",
    title: "Sewer Cleanout Installation Cost in Austin",
    routeLabel: "Sewer Cleanout Installation Cost",
    problem: "No sewer cleanout accessible in yard",
    tableLabel: "Sewer cleanout installation",
    ironcladPrice: "$750",
    austinRange: "$400-$1,200",
    askWhyOver: "Over $1,400",
    detailHeading: "Sewer Cleanout Installation",
  },
  {
    slug: "bathroom-remodel-plumbing-cost-austin",
    title: "Bathroom Remodel Plumbing Cost in Austin",
    routeLabel: "Bathroom Remodel Plumbing Cost",
    problem: "Remodeling a bathroom, need plumbing moved",
    tableLabel: "Bathroom remodel plumbing rough-in",
    ironcladPrice: "$3,500",
    austinRange: "$2,000-$6,000",
    askWhyOver: "Over $7,000 without detailed scope",
    detailHeading: "Bathroom Remodel Plumbing Rough-In",
  },
  {
    slug: "kitchen-remodel-plumbing-cost-austin",
    title: "Kitchen Remodel Plumbing Cost in Austin",
    routeLabel: "Kitchen Remodel Plumbing Cost",
    problem: "Remodeling a kitchen, need plumbing relocated",
    tableLabel: "Kitchen remodel plumbing rough-in",
    ironcladPrice: "$2,500",
    austinRange: "$1,500-$4,500",
    askWhyOver: "Over $5,000 without detailed scope",
    detailHeading: "Kitchen Remodel Plumbing Rough-In",
  },
  {
    slug: "slab-leak-reroute-cost-austin",
    title: "Slab Leak Reroute Cost in Austin",
    routeLabel: "Slab Leak Reroute Cost",
    problem: "Slab leak confirmed, need pipe rerouted",
    tableLabel: "Slab leak reroute (through attic/walls)",
    ironcladPrice: "$3,500",
    austinRange: "$2,000-$5,500",
    askWhyOver: "Over $6,000 without showing you the plan",
    detailHeading: "Slab Leak Reroute (Through Attic/Walls)",
  },
  {
    slug: "bathtub-drain-and-overflow-repair-cost-austin",
    title: "Bathtub Drain and Overflow Repair Cost in Austin",
    routeLabel: "Bathtub Drain and Overflow Repair Cost",
    problem: "Tub drains slowly / overflow broken",
    tableLabel: "Bathtub drain and overflow repair",
    ironcladPrice: "$275",
    austinRange: "$175-$425",
    askWhyOver: "Over $500",
    detailHeading: "Bathtub Drain and Overflow Repair",
  },
  {
    slug: "refrigerator-water-line-installation-cost-austin",
    title: "Refrigerator Water Line Installation Cost in Austin",
    routeLabel: "Refrigerator Water Line Installation Cost",
    problem: "Need water line to fridge/ice maker",
    tableLabel: "Refrigerator water line installation",
    ironcladPrice: "$225",
    austinRange: "$125-$350",
    askWhyOver: "Over $425",
    detailHeading: "Refrigerator Water Line Installation",
  },
  {
    slug: "outdoor-gas-line-installation-cost-austin",
    title: "Outdoor Gas Line Installation Cost in Austin",
    routeLabel: "Outdoor Gas Line Installation Cost",
    problem: "Gas line for outdoor grill, fire pit, or pool heater",
    tableLabel: "Outdoor gas line run (long)",
    ironcladPrice: "$1,200",
    austinRange: "$700-$2,500",
    askWhyOver: "Over $3,000",
    detailHeading: "Outdoor Gas Line Run (Long)",
  },
  {
    slug: "whole-house-carbon-filtration-cost-austin",
    title: "Whole-House Carbon Filtration Cost in Austin",
    routeLabel: "Whole-House Carbon Filtration Cost",
    problem: "Whole-house water filter (not softener)",
    tableLabel: "Whole-house carbon filtration",
    ironcladPrice: "$1,800",
    austinRange: "$1,000-$3,000",
    askWhyOver: "Over $3,500",
    detailHeading: "Whole-House Carbon Filtration System",
  },
  {
    slug: "toilet-flange-repair-cost-austin",
    title: "Toilet Flange Repair Cost in Austin",
    routeLabel: "Toilet Flange Repair Cost",
    problem: "Toilet flange is cracked / broken",
    tableLabel: "Toilet flange repair or replacement",
    ironcladPrice: "$275",
    austinRange: "$175-$400",
    askWhyOver: "Over $500",
    detailHeading: "Toilet Flange Repair or Replacement",
  },
  {
    slug: "bidet-seat-installation-cost-austin",
    title: "Bidet Seat Installation Cost in Austin",
    routeLabel: "Bidet Seat Installation Cost",
    problem: "Want a bidet seat installed",
    tableLabel: "Bidet seat installation (electric)",
    ironcladPrice: "$250",
    austinRange: "$150-$400",
    askWhyOver: "Over $500",
    detailHeading: "Bidet Seat Installation (Electric)",
  },
  {
    slug: "gas-appliance-connection-cost-austin",
    title: "Gas Appliance Connection Cost in Austin",
    routeLabel: "Gas Appliance Connection Cost",
    problem: "Gas range or dryer needs hooking up",
    tableLabel: "Gas appliance connection",
    ironcladPrice: "$275",
    austinRange: "$175-$450",
    askWhyOver: "Over $525",
    detailHeading: "Gas Appliance Connection (Range or Dryer)",
  },
  {
    slug: "water-pressure-booster-pump-cost-austin",
    title: "Water Pressure Booster Pump Cost in Austin",
    routeLabel: "Water Pressure Booster Pump Cost",
    problem: "Water pressure is too low throughout house",
    tableLabel: "Water pressure booster pump",
    ironcladPrice: "$900",
    austinRange: "$600-$1,500",
    askWhyOver: "Over $1,800",
    detailHeading: "Water Pressure Booster Pump",
  },
  {
    slug: "pipe-insulation-cost-austin",
    title: "Pipe Insulation Cost in Austin",
    routeLabel: "Pipe Insulation Cost",
    problem: "Crawlspace or under-house pipes need insulating",
    tableLabel: "Pipe insulation (freeze protection)",
    ironcladPrice: "$400",
    austinRange: "$200-$700",
    askWhyOver: "Over $850",
    detailHeading: "Pipe Insulation (Freeze Protection)",
  },
  {
    slug: "p-trap-repair-cost-austin",
    title: "P-Trap Repair Cost in Austin",
    routeLabel: "P-Trap Repair Cost",
    problem: "Drain smell coming from floor or shower",
    tableLabel: "P-trap replacement or dry trap repair",
    ironcladPrice: "$175",
    austinRange: "$100-$275",
    askWhyOver: "Over $350",
    detailHeading: "P-Trap Replacement or Dry Trap Repair",
  },
];

export const PRICING_SERVICE_GUIDE_SPECS_BY_SLUG = new Map(
  PRICING_SERVICE_GUIDE_SPECS.map((spec) => [spec.slug, spec]),
);
