import {
  SITE_ORIGIN,
  STANDARD_HEADLINES,
  STANDARD_PROMOTION_DESCRIPTION,
  STANDARD_PROMOTION_HEADLINE,
  standardDescriptions,
} from "./manifest-shared";
import { exact, phrase, type CampaignSpec } from "./types";
import { SERVICE_CAMPAIGN_ROUTING_NEGATIVES } from "./campaigns-service-gaps";
import { TARGET_CPA_MICROS } from "./launch-config";

export const DRAIN_SEWER: CampaignSpec = {
  key: "drain-sewer",
  name: "Drain & Sewer",
  budgetMicros: "20000000",
  cpcCapMicros: "18000000",
  targetCpaMicros: TARGET_CPA_MICROS,
  launchEnabled: true,
  crossNegatives: [
    "emergency", "24 hour", "open now", "water heater", "tankless", "slab leak", "repipe",
    "ac drain", "air conditioner drain", "condensate drain", "dishwasher",
    "apple cider vinegar", "baking soda", "bleach", "vinegar", "home recipe",
    "home remedies", "home remedy", "homemade", "best homemade drain cleaner",
    "best thing to unclog", "best way to unclog", "what can i use to unclog drain",
    "what's good to unclog", "whats good to unclog", "toilet overflow solution",
    "chemical drain cleaner", "chemical drain opener", "drain opener", "drain solve",
    "drano", "liquid fire", "thrift drain cleaner", "best drain snake",
    "drain machine", "drain snake tool", "electric eel", "flex shaft", "sewer machine",
    "snake drain tool", "snake for plumbing", "tool to unclog",
    ...SERVICE_CAMPAIGN_ROUTING_NEGATIVES["drain-sewer"],
  ],
  residentialFilter: true,
  promotionHeadline: "Drain Cleaning for $69",
  headlines: STANDARD_HEADLINES,
  descriptions: standardDescriptions("Drain cleaning for $69. Call Ironclad today."),
  adGroups: [
    {
      name: "Drain Cleaning & Drain Clearing",
      finalUrl: `${SITE_ORIGIN}/plumbing/drain-clearing`,
      primaryHeadline: "Drain Cleaning Experts",
      additionalHeadlines: [
        "Drain Cleaning Near Me",
        "Drain Clearing Service",
        "Clear Slow & Clogged Drains",
        "Get Drains Flowing Again",
        "Professional Drain Snaking",
        "Clog & Backup Clearing",
        "Austin Drain Cleaning",
        "Same-Day Drain Availability",
      ],
      outcomeDescription: "We'll clear the clog and help prevent it from coming back.",
      keywords: [
        ...exact("drain cleaning", "drain cleaning near me", "drain cleaning austin", "drain clearing", "drain clearing service"),
        ...phrase("drain clearing near me", "drain cleaning service", "drain cleaning cost", "drain snaking", "snake a drain", "drain snake service", "rooter service", "drain rooter", "sewer rooter", "drain cleaning company"),
      ],
    },
    {
      name: "Clogged Drain",
      finalUrl: `${SITE_ORIGIN}/plumbing/clogged-drain`,
      primaryHeadline: "Clogged Drain Experts",
      additionalHeadlines: [
        "Clogged Drain Plumber",
        "Unclog Your Drain",
        "Slow Drain Help",
        "Get Your Drain Flowing",
        "Kitchen & Bathroom Clogs",
        "Clear Shower Drain Clogs",
        "Recurring Clog Diagnosis",
        "Austin Clogged Drain Help",
      ],
      outcomeDescription: "Get the drain flowing again and help keep the clog from coming back.",
      keywords: [
        ...exact("clogged drain plumber"),
        ...phrase("clogged kitchen sink plumber", "unclog drain plumber", "drain unclogging service", "clear clogged drain", "slow drain plumber", "clogged shower drain plumber", "clogged bathtub drain plumber", "sink wont drain"),
      ],
    },
    {
      name: "Sewer Line",
      finalUrl: `${SITE_ORIGIN}/plumbing/sewer-services`,
      primaryHeadline: "Sewer Line Repair Experts",
      additionalHeadlines: [
        "Sewer Line Repair",
        "Sewer Line Replacement",
        "Main Line Clog?",
        "Find the Sewer Line Break",
        "Sewer Repair Options",
        "Camera-First Sewer Service",
        "Austin Sewer Line Plumber",
        "Repair or Replace Sewer Line",
      ],
      outcomeDescription: "Find the break and choose the right sewer repair for your home.",
      promotionHeadline: STANDARD_PROMOTION_HEADLINE,
      promotionDescription: STANDARD_PROMOTION_DESCRIPTION,
      keywords: [
        ...exact("sewer line repair", "sewer line replacement"),
        ...phrase("main line clog", "clogged main line", "main drain clog", "sewer line repair cost", "sewer line replacement cost", "sewer smell in house"),
        {
          finalUrl: `${SITE_ORIGIN}/plumbing/drain-clearing`,
          matchType: "PHRASE",
          text: "sewer line cleaning",
        },
      ],
    },
    {
      name: "Sewer Camera & Scope",
      finalUrl: `${SITE_ORIGIN}/plumbing/sewer-camera-inspection`,
      primaryHeadline: "Sewer Camera Experts",
      additionalHeadlines: [
        "Sewer Camera Inspection",
        "Sewer Scope Inspection",
        "See Inside Your Sewer Line",
        "Find Blockages & Damage",
        "Recorded Sewer Inspection",
        "Diagnose Recurring Backups",
        "Camera Before Sewer Repair",
        "Austin Sewer Line Camera",
      ],
      outcomeDescription: "See exactly what is blocking or damaging your sewer line.",
      promotionHeadline: STANDARD_PROMOTION_HEADLINE,
      promotionDescription: STANDARD_PROMOTION_DESCRIPTION,
      keywords: [
        ...exact("sewer camera inspection", "sewer scope inspection"),
        ...phrase("sewer camera inspection cost", "sewer inspection before buying house", "plumbing inspection home purchase", "sewer line camera", "sewer scope near me"),
      ],
    },
    {
      name: "Hydro Jetting",
      finalUrl: `${SITE_ORIGIN}/plumbing/hydro-jetting`,
      primaryHeadline: "Hydro Jetting Experts",
      additionalHeadlines: [
        "Hydro Jetting Near Me",
        "Hydro Jet Drain Cleaning",
        "Clear Heavy Drain Buildup",
        "Restore Drain Flow",
        "Hydro Jet Grease & Roots",
        "High-Pressure Line Cleaning",
        "Clear Recurring Main Clogs",
        "Austin Hydro Jetting",
      ],
      outcomeDescription: "Clear heavy buildup and restore flow through your drain or sewer line.",
      promotionHeadline: STANDARD_PROMOTION_HEADLINE,
      promotionDescription: STANDARD_PROMOTION_DESCRIPTION,
      keywords: [
        ...exact("hydro jetting"),
        ...phrase("hydro jetting near me", "hydro jetting cost", "hydro jet drain cleaning", "sewer jetting service"),
      ],
    },
    {
      name: "Trenchless",
      finalUrl: `${SITE_ORIGIN}/plumbing/trenchless-sewer-repair`,
      primaryHeadline: "Trenchless Sewer Experts",
      additionalHeadlines: [
        "Trenchless Sewer Repair",
        "Trenchless Pipe Lining",
        "Repair With Less Digging",
        "Less Yard Disruption",
        "Trenchless Sewer Lining",
        "Pipe Bursting Options",
        "Replace Sewer With Less Dig",
        "Austin Trenchless Plumber",
      ],
      outcomeDescription: "Repair your sewer line with less digging and less disruption.",
      promotionHeadline: STANDARD_PROMOTION_HEADLINE,
      promotionDescription: STANDARD_PROMOTION_DESCRIPTION,
      keywords: [
        ...exact("trenchless sewer repair"),
        ...phrase("trenchless sewer replacement", "trenchless pipe lining", "pipe bursting sewer", "trenchless sewer repair cost"),
      ],
    },
    {
      name: "Toilet Repair & Install",
      finalUrl: `${SITE_ORIGIN}/plumbing/toilet-repair-installation`,
      primaryHeadline: "Toilet Repair Experts",
      additionalHeadlines: [
        "Toilet Repair Near Me",
        "Toilet Installation",
        "Clogged Toilet Plumber",
        "Fix Leaks & Flushing Issues",
        "Running Toilet Repair",
        "Toilet Leaking at Base",
        "New Toilet Replacement",
        "Fix Weak Toilet Flushes",
      ],
      outcomeDescription: "Get your toilet working properly without guessing at the cause.",
      promotionHeadline: STANDARD_PROMOTION_HEADLINE,
      promotionDescription: STANDARD_PROMOTION_DESCRIPTION,
      keywords: [
        ...exact("toilet repair", "toilet installation"),
        {
          finalUrl: `${SITE_ORIGIN}/plumbing/toilet-replacement`,
          matchType: "EXACT",
          text: "toilet replacement",
        },
        ...phrase("clogged toilet plumber", "toilet leaking at base", "toilet repair near me", "toilet installation cost", "install new toilet", "toilet wont flush plumber"),
      ],
    },
  ],
};
