import {
  SITE_ORIGIN,
  STANDARD_HEADLINES,
  STANDARD_PROMOTION_HEADLINE,
  standardDescriptions,
} from "./manifest-shared";
import { TARGET_CPA_MICROS } from "./launch-config";
import { exact, phrase, type CampaignSpec } from "./types";
import { SERVICE_CAMPAIGN_ROUTING_NEGATIVES } from "./campaigns-service-gaps";

export const LEAKS_LINES: CampaignSpec = {
  key: "leaks-lines",
  name: "Leaks & Lines",
  budgetMicros: "15000000",
  cpcCapMicros: "20000000",
  targetCpaMicros: TARGET_CPA_MICROS,
  launchEnabled: true,
  crossNegatives: [
    "emergency", "24 hour", "open now", "water heater", "tankless", "drain cleaning",
    "drain clearing", "leak detection system", "leak detector", "water leak sensor",
    ...SERVICE_CAMPAIGN_ROUTING_NEGATIVES["leaks-lines"],
  ],
  exactCrossNegatives: ["plumbing austin"],
  residentialFilter: true,
  promotionHeadline: STANDARD_PROMOTION_HEADLINE,
  headlines: STANDARD_HEADLINES,
  descriptions: standardDescriptions(),
  adGroups: [
    {
      name: "Leak Detection",
      finalUrl: `${SITE_ORIGIN}/leak-detection`,
      primaryHeadline: "Leak Detection Experts",
      additionalHeadlines: [
        "Leak Detection Near Me",
        "Water Leak Detection",
        "Find Hidden Water Leaks",
        "Pinpoint the Leak",
        "Hidden Leak Detection",
        "High Water Bill?",
        "Hear Water in the Wall?",
        "Austin Leak Detection",
      ],
      outcomeDescription: "We'll pinpoint the leak and recommend the right repair.",
      keywords: [
        ...exact("leak detection", "leak detection near me"),
        ...phrase("water leak detection service", "high water bill leak", "leak detection cost", "water meter spinning", "hear water running in walls", "find water leak in house"),
      ],
    },
    {
      name: "Slab Leak",
      finalUrl: `${SITE_ORIGIN}/plumbing/slab-leak-repair`,
      primaryHeadline: "Slab Leak Experts",
      additionalHeadlines: [
        "Slab Leak Repair",
        "Slab Leak Detection",
        "Warm Spot on the Floor?",
        "Find Slab Leaks Early",
        "Slab Leak Plumber",
        "Foundation Leak Detection",
        "Non-Invasive Leak Search",
        "Austin Slab Leak Repair",
      ],
      outcomeDescription: "Find the slab leak before it causes more damage to your home.",
      keywords: [
        ...exact("slab leak repair", "slab leak detection"),
        ...phrase("slab leak repair cost", "warm spot on floor", "slab leak plumber", "foundation leak plumber"),
      ],
    },
    {
      name: "Water Line",
      finalUrl: `${SITE_ORIGIN}/plumbing/water-line-repair`,
      primaryHeadline: "Water Line Repair Experts",
      additionalHeadlines: [
        "Water Line Repair",
        "Main Water Line Repair",
        "Water Line Replacement",
        "Restore Your Water Service",
        "Broken Main Water Line",
        "Wet Spot in the Yard?",
        "Main Line Leak Repair",
        "Austin Water Line Repair",
      ],
      outcomeDescription: "Find the break and restore reliable water service to your home.",
      keywords: [
        ...exact("water line repair"),
        ...phrase("main water line repair", "water line replacement", "water main leak", "wet spot in yard", "water line repair cost", "broken water line"),
      ],
    },
    {
      name: "Pipe Repair",
      finalUrl: `${SITE_ORIGIN}/plumbing/water-line-repair`,
      primaryHeadline: "Pipe Repair Experts",
      additionalHeadlines: [
        "Pipe Leak Repair",
        "Broken Pipe Repair",
        "Leaking Pipe Plumber",
        "Repair Pipes Before Damage",
        "Copper Pipe Repair",
        "Pinhole Leak Repair",
        "Under-Sink Pipe Leak",
        "Austin Pipe Leak Repair",
      ],
      outcomeDescription: "Fix the leaking or broken pipe before it causes more damage.",
      keywords: [
        ...exact("pipe repair"),
        ...phrase("pipe leak repair", "broken pipe repair", "pinhole leak", "plumbing leak repair", "leaking pipe under sink", "pipe repair plumber"),
        {
          finalUrl: `${SITE_ORIGIN}/plumbing/leak-repair`,
          matchType: "PHRASE",
          text: "copper pipe repair",
        },
      ],
    },
    {
      name: "Gas Line",
      finalUrl: `${SITE_ORIGIN}/plumbing/gas-line-services`,
      primaryHeadline: "Gas Line Service Experts",
      additionalHeadlines: [
        "Gas Line Repair",
        "Gas Line Installation",
        "Gas Line Plumber",
        "Safe Gas Line Service",
        "Gas Leak Testing & Repair",
        "Stove & Grill Gas Lines",
        "Code-Compliant Gas Work",
        "Austin Gas Line Plumber",
      ],
      outcomeDescription: "Find the gas-line problem and get it repaired safely.",
      keywords: [
        ...exact("gas line repair", "gas line installation"),
        ...phrase("gas line plumber", "gas leak repair", "gas line for stove", "gas line for grill", "gas line installation cost", "smell gas in house plumber"),
      ],
    },
    {
      name: "Repiping",
      finalUrl: `${SITE_ORIGIN}/plumbing/repiping`,
      primaryHeadline: "Whole Home Repiping Experts",
      additionalHeadlines: [
        "Whole House Repipe",
        "Home Repiping Company",
        "PEX Repiping",
        "Replace Old Home Pipes",
        "Whole House Pipe Replacement",
        "Replace Corroded Pipes",
        "PEX Repipe Options",
        "Austin Repiping Company",
      ],
      outcomeDescription: "Know which pipes need replacing—and which ones do not.",
      keywords: [
        ...exact("whole house repipe"),
        ...phrase("repiping company", "repipe cost", "whole house repipe cost", "pex repipe", "repipe specialist", "replace old pipes house"),
      ],
    },
  ],
};
