import {
  CORE_COMPETITOR_NEGATIVES,
  SITE_ORIGIN,
  STANDARD_HEADLINES,
  STANDARD_PROMOTION_HEADLINE,
  standardDescriptions,
} from "./manifest-shared";
import { TARGET_CPA_MICROS } from "./launch-config";
import { exact, phrase, type CampaignSpec } from "./types";
import { SERVICE_CAMPAIGN_ROUTING_NEGATIVES } from "./campaigns-service-gaps";

export const EMERGENCY: CampaignSpec = {
  key: "emergency",
  name: "Emergency",
  budgetMicros: "15000000",
  cpcCapMicros: "30000000",
  targetCpaMicros: TARGET_CPA_MICROS,
  launchEnabled: true,
  crossNegatives: [
    "water heater", "tankless", "drain cleaning", "drain clearing", "leak detection", "repipe",
    ...CORE_COMPETITOR_NEGATIVES,
    ...SERVICE_CAMPAIGN_ROUTING_NEGATIVES.emergency,
  ],
  residentialFilter: true,
  promotionHeadline: STANDARD_PROMOTION_HEADLINE,
  headlines: STANDARD_HEADLINES,
  descriptions: standardDescriptions(),
  adGroups: [
    {
      name: "Emergency Plumber",
      finalUrl: `${SITE_ORIGIN}/emergency-plumbing`,
      primaryHeadline: "Emergency Plumbing Experts",
      additionalHeadlines: [
        "Emergency Plumber Near Me",
        "Emergency Plumbing Repair",
        "Help Stop Water Damage",
        "Call for Plumbing Help",
        "24 Hour Austin Plumber",
        "Plumber Open Now",
        "Active Water Leak Help",
        "No Water in Your House?",
      ],
      outcomeDescription: "Stop the damage fast and get the right repair for your home.",
      keywords: [
        ...exact("emergency plumber", "emergency plumber austin", "emergency plumber near me", "24 hour plumber", "plumber open now", "no water in house"),
        ...phrase("emergency plumbing service", "24 hour plumber near me", "active water leak", "water leak emergency", "emergency plumbing repair", "no water coming out of faucet"),
      ],
    },
    {
      name: "Burst Pipe",
      finalUrl: `${SITE_ORIGIN}/plumbing/burst-pipe-repair`,
      primaryHeadline: "Burst Pipe Repair Experts",
      additionalHeadlines: [
        "Burst Pipe Plumber",
        "Broken Pipe Emergency",
        "Stop Water Damage",
        "Burst Pipe Repair Near Me",
        "Emergency Pipe Repair",
        "Water Pipe Burst?",
        "Shutoff & Repair Help",
        "Austin Burst Pipe Repair",
      ],
      outcomeDescription: "Stop the water fast and get the broken pipe repaired.",
      keywords: [
        ...exact("burst pipe repair"),
        ...phrase("burst pipe plumber", "pipe burst in house", "broken pipe emergency", "water pipe burst", "burst pipe repair cost"),
      ],
    },
    {
      name: "Sewer Backup",
      finalUrl: `${SITE_ORIGIN}/plumbing/sewer-services`,
      primaryHeadline: "Sewer Backup Experts",
      additionalHeadlines: [
        "Sewer Backup Plumber",
        "Sewage Backup Help",
        "Clear the Sewer Backup",
        "Find the Cause of Backups",
        "Main Sewer Backup Help",
        "Multiple Drains Backing Up",
        "Emergency Main Line Help",
        "Austin Sewer Backup Help",
      ],
      outcomeDescription: "Clear the backup and find the cause before it happens again.",
      keywords: phrase("sewer backup plumber", "sewage backup in house", "sewer backing up into shower", "raw sewage in house", "sewer backup emergency"),
    },
    {
      name: "Overflowing Toilet",
      finalUrl: `${SITE_ORIGIN}/plumbing/toilet-repair-installation`,
      primaryHeadline: "Overflowing Toilet Experts",
      additionalHeadlines: [
        "Overflowing Toilet Plumber",
        "Toilet Overflow Help",
        "Stop the Toilet Overflow",
        "Get Your Toilet Working",
        "Toilet Won't Stop Overflowing",
        "Emergency Toilet Plumber",
        "Fix Toilet Backup Fast",
        "Austin Toilet Overflow Help",
      ],
      outcomeDescription: "Stop the overflow and get your toilet working again.",
      keywords: phrase("overflowing toilet plumber", "toilet overflowing wont stop", "toilet overflowing emergency"),
    },
    {
      name: "After-Hours & Weekend",
      finalUrl: `${SITE_ORIGIN}/emergency-plumbing`,
      primaryHeadline: "After-Hours Plumbing Experts",
      additionalHeadlines: [
        "After Hours Plumber",
        "Weekend Plumber Near Me",
        "Plumber Open Nights",
        "Saturday & Sunday Plumbing",
        "24 Hour Plumbing Service",
        "Sunday Plumber",
        "Late Night Plumbing Help",
        "Austin Weekend Plumber",
      ],
      outcomeDescription: "Get the plumbing problem handled tonight or this weekend.",
      keywords: [
        ...exact("weekend plumber", "sunday plumber", "after hours plumber"),
        ...phrase("plumber open sunday", "plumber open on weekend", "late night plumber", "plumber open saturday", "plumber open late"),
      ],
    },
  ],
};

export const WATER_HEATER: CampaignSpec = {
  key: "water-heater",
  name: "Water Heater",
  budgetMicros: "20000000",
  cpcCapMicros: "22000000",
  targetCpaMicros: TARGET_CPA_MICROS,
  launchEnabled: true,
  crossNegatives: [
    "emergency", "24 hour", "open now", "drain", "sewer",
    "110 volt", "110v", "calculator", "gallons per minute", "gpm", "kw",
    "model number", "model numbers", "spex3012", "lowe's",
    ...CORE_COMPETITOR_NEGATIVES,
    ...SERVICE_CAMPAIGN_ROUTING_NEGATIVES["water-heater"],
  ],
  exactCrossNegatives: [
    "best non condensing tankless water heater",
    "navien electric tankless water heater",
    "rinnai tankless water heater",
  ],
  residentialFilter: true,
  promotionHeadline: "Up to $300 Off New Heaters",
  headlines: STANDARD_HEADLINES,
  descriptions: standardDescriptions(
    "New customers save up to $300 on a new water heater. Call Ironclad today.",
  ),
  adGroups: [
    {
      name: "Repair & No Hot Water",
      finalUrl: `${SITE_ORIGIN}/plumbing/water-heater-repair`,
      primaryHeadline: "Water Heater Repair Experts",
      additionalHeadlines: [
        "Water Heater Repair",
        "No Hot Water?",
        "Hot Water Heater Repair",
        "Repair or Replace?",
        "Pilot Light Won't Stay Lit",
        "Water Heater Not Heating",
        "Not Enough Hot Water?",
        "Austin Hot Water Repair",
      ],
      outcomeDescription: "Know whether you need a water heater repair or replacement before you decide.",
      keywords: [
        ...exact("water heater repair", "water heater repair near me", "water heater repair austin"),
        ...phrase("hot water heater repair", "no hot water", "no hot water plumber", "water heater pilot light wont stay lit", "water heater not heating", "not enough hot water"),
      ],
    },
    {
      name: "Replacement",
      finalUrl: `${SITE_ORIGIN}/plumbing/water-heaters`,
      primaryHeadline: "Water Heater Replacement",
      additionalHeadlines: [
        "Replace Your Water Heater",
        "Leaking Water Heater?",
        "Choose the Right Water Heater",
        "Water Heater Near Me",
        "Water Heater Replacement Cost",
        "Tank Water Heater Options",
        "Replace a Leaking Heater",
        "Austin Heater Replacement",
      ],
      outcomeDescription: "Choose the right water heater for your home and your hot-water needs.",
      keywords: [
        ...exact("water heater replacement"),
        ...phrase("water heater replacement cost", "leaking water heater", "water heater leaking from bottom", "water heater not working", "replace water heater", "water heater replacement near me"),
      ],
    },
    {
      name: "Installation",
      finalUrl: `${SITE_ORIGIN}/plumbing/water-heater-installation`,
      primaryHeadline: "Water Heater Installation",
      additionalHeadlines: [
        "Water Heater Installers",
        "New Water Heater Installed",
        "Gas & Electric Options",
        "Installed for Your Home",
        "40 & 50 Gallon Installation",
        "Code-Compliant Installation",
        "Tank Water Heater Install",
        "Austin Water Heater Install",
      ],
      outcomeDescription: "Get the right water heater installed correctly for your home.",
      keywords: [
        ...exact("water heater installation"),
        ...phrase("new water heater installed", "40 gallon water heater installed", "50 gallon water heater installed", "water heater install cost", "water heater installation near me"),
      ],
    },
    {
      name: "Tankless",
      finalUrl: `${SITE_ORIGIN}/plumbing/tankless-water-heaters`,
      primaryHeadline: "Tankless Water Heater Experts",
      additionalHeadlines: [
        "Tankless Water Heater",
        "Tankless Repair & Install",
        "Is Tankless Right for You?",
        "Tankless Plumber Near Me",
        "Tankless Installation",
        "Tankless Water Heater Repair",
        "Tankless Flush Service",
        "Austin Tankless Installer",
      ],
      outcomeDescription: "Find out whether a tankless water heater is right for your home.",
      keywords: [
        ...exact("tankless water heater repair", "tankless water heater installation"),
        ...phrase("tankless water heater installer near me", "tankless water heater cost installed", "tankless water heater replacement", "tankless water heater flush"),
      ],
    },
    {
      name: "Brand + Service",
      finalUrl: `${SITE_ORIGIN}/plumbing/water-heater-repair`,
      primaryHeadline: "Water Heater Brand Experts",
      additionalHeadlines: [
        "Water Heater Brand Repair",
        "Repair for Many Brands",
        "Tank & Tankless Repair",
        "Help for Your Heater Model",
        "Rheem Water Heater Repair",
        "Rinnai Tankless Repair",
        "Navien Tankless Repair",
        "A.O. Smith Heater Repair",
      ],
      outcomeDescription: "Get the right repair for your water heater brand and model.",
      keywords: phrase("rheem water heater repair", "rinnai tankless repair", "navien tankless repair", "ao smith water heater repair", "bradford white water heater repair", "state water heater repair"),
    },
  ],
};
