import type { DataDeskProduct } from "./types";

export const MARKET_AND_PROPERTY_PRODUCTS: DataDeskProduct[] = [
  {
    rank: 2,
    slug: "austin-plumbing-cost-index",
    title: "Austin Plumbing Cost Index",
    shortTitle: "Plumbing Cost Index",
    metaTitle: "Austin Plumbing Cost Index | Ironclad Data Desk",
    metaDescription:
      "Explore methodology-backed Austin price ranges for common plumbing repairs, replacements and emergencies using anonymized completed work.",
    category: "market-costs",
    citationPotential: 5,
    embedPotential: 3,
    summary: "A reviewed index of actual Austin plumbing price ranges, sample sizes, changes over time and major cost drivers.",
    signals: ["Median and percentile ranges", "Quarter-over-quarter movement", "Sample size and job characteristics"],
    sources: ["Anonymized Ironclad estimates", "Anonymized completed invoices", "Documented category and suppression rules"],
    cadence: "Planned nightly internal imports and a reviewed quarterly public index.",
    audiences: ["Consumer and real-estate reporters", "Property managers", "Homeowners, buyers and inspectors"],
    editorialUse: "A local, repeatable benchmark for reporting what common Austin plumbing work has actually cost.",
    guardrail: "Small samples will be suppressed, and historical ranges will not be presented as a quote or guaranteed future price.",
  },
  {
    rank: 4,
    slug: "austin-plumbing-permit-tracker",
    title: "Austin Plumbing Permit and Remodel Tracker",
    shortTitle: "Permit and Remodel Tracker",
    metaTitle: "Austin Plumbing Permit & Remodel Tracker | Ironclad",
    metaDescription:
      "Search and follow Austin plumbing permits, declared project values, remodel categories and neighborhood trends in a simpler public tracker.",
    category: "market-costs",
    citationPotential: 5,
    embedPotential: 4,
    summary: "A searchable, plain-language view of Austin plumbing permits and remodeling activity by place and project type.",
    signals: ["Permit and project locations", "Plain-language project categories", "ZIP and neighborhood trends"],
    sources: ["City of Austin issued construction permits", "Public project descriptions", "Public declared valuations"],
    cadence: "Planned nightly imports with reviewed weekly and monthly summaries.",
    audiences: ["Real-estate and development reporters", "Agents and builders", "Neighborhood organizations"],
    editorialUse: "A recurring view of where Austin homeowners are investing in plumbing and remodeling work.",
    guardrail: "Classifications will be documented, and every record will link back to its controlling public source where available.",
  },
  {
    rank: 5,
    slug: "austin-home-plumbing-risk-report",
    title: "Austin Home Plumbing Risk Map and Address Report",
    shortTitle: "Home Plumbing Risk Report",
    metaTitle: "Austin Home Plumbing Risk Map & Address Report",
    metaDescription:
      "Research an Austin address for construction-era context, public permits, flood exposure and common plumbing questions before inspection.",
    category: "property-research",
    citationPotential: 5,
    embedPotential: 5,
    summary: "A pre-inspection address briefing for understanding public property context and questions worth investigating.",
    signals: ["Construction-era context", "Public permit history", "Flood and freeze exposure"],
    sources: ["Census housing data", "City of Austin permit records", "FEMA and weather data"],
    cadence: "Planned nightly permit updates, annual Census updates and versioned hazard-layer refreshes.",
    audiences: ["Homebuyers and sellers", "Realtors and inspectors", "Housing and neighborhood reporters"],
    editorialUse: "A way to compare structural and infrastructure context across Austin's older and newer housing areas.",
    guardrail: "The report will be a pre-inspection briefing, not an inspection; unverified materials will be described only as possibilities.",
  },
  {
    rank: 9,
    slug: "austin-home-services-cost-index",
    title: "Austin Home Services Cost Index",
    shortTitle: "Home Services Cost Index",
    metaTitle: "Austin Home Services Cost Index | Ironclad Data Desk",
    metaDescription:
      "Compare aggregated Austin costs for plumbing, HVAC, electrical, roofing, restoration and other home services using completed local work.",
    category: "market-costs",
    citationPotential: 4.5,
    embedPotential: 3,
    summary: "A multi-trade index designed to measure the changing cost of maintaining an Austin home from completed work.",
    signals: ["Median completed-job costs", "Trade and project categories", "Historical maintenance-cost trends"],
    sources: ["Standardized contributor submissions", "Anonymized historical jobs", "Published validation and threshold rules"],
    cadence: "Planned secure monthly imports and a reviewed quarterly release.",
    audiences: ["Business and housing reporters", "Agents and homebuyers", "Qualified home-service contributors"],
    editorialUse: "A broader local benchmark for stories about the real cost of owning and maintaining an Austin home.",
    guardrail: "Only aggregated historical information will be published; the program will not coordinate company-specific or future pricing.",
  },
  {
    rank: 11,
    slug: "austin-contractor-license-permit-search",
    title: "Austin Contractor License and Permit Transparency Search",
    shortTitle: "Contractor and Permit Search",
    metaTitle: "Austin Contractor License & Permit Search | Ironclad",
    metaDescription:
      "Find official Austin contractor, license, permit and address lookup paths with plain-language status notes and consumer verification steps.",
    category: "property-research",
    citationPotential: 4,
    embedPotential: 4,
    summary: "A neutral verification guide that makes official contractor and permit records easier for consumers to find and understand.",
    signals: ["Official verification links", "Permit and case history", "What each record does and does not prove"],
    sources: ["Austin AB+C public search", "Texas license authorities", "Jurisdiction-specific permit guidance"],
    cadence: "Planned link and instruction checks, with updates when official systems change.",
    audiences: ["Homeowners and buyers", "Consumer journalists", "Agents, inspectors and neighborhood groups"],
    editorialUse: "A source-linked checklist for verifying a contractor and permitted work before signing.",
    guardrail: "Unsupported systems will receive a guided official lookup, not scraping that bypasses agency restrictions.",
  },
  {
    rank: 12,
    slug: "austin-leak-water-waste-economics",
    title: "Austin Leak and Water-Waste Economics Dashboard",
    shortTitle: "Leak and Water-Waste Economics",
    metaTitle: "Austin Leak & Water-Waste Economics Dashboard",
    metaDescription:
      "Translate toilet, faucet, irrigation and hidden leaks into gallons, Austin bill impact and annual cost using versioned local rate assumptions.",
    category: "market-costs",
    citationPotential: 4,
    embedPotential: 5,
    summary: "A local economics dashboard turning measured or estimated leak flow into understandable water loss and bill impact.",
    signals: ["Gallons lost over time", "Estimated tiered bill impact", "Equivalent household water uses"],
    sources: ["Austin utility rate schedules", "User meter or flow observations", "Anonymized verified Ironclad measurements"],
    cadence: "Planned rate monitoring with versioned assumptions and automatic recalculation.",
    audiences: ["Drought and utility reporters", "HOAs and property managers", "Homeowners and conservation programs"],
    editorialUse: "A local way to make the cost and scale of otherwise invisible water waste understandable.",
    guardrail: "Every estimate will show its rate version and assumptions; observed and inferred flow will be labeled separately.",
  },
  {
    rank: 15,
    slug: "homebuyer-inspection-action-planner",
    title: "Homebuyer and Inspection Action Planner",
    shortTitle: "Inspection Action Planner",
    metaTitle: "Austin Homebuyer Inspection Action Planner | Ironclad",
    metaDescription:
      "Turn common Austin plumbing inspection findings into prioritized questions, urgency context and an appropriate next professional to contact.",
    category: "property-research",
    citationPotential: 3,
    embedPotential: 5,
    summary: "A calm, structured next-step plan for buyers who receive a plumbing-related inspection finding.",
    signals: ["Finding explanations", "Urgency and investigation path", "Questions for the appropriate professional"],
    sources: ["Expert-reviewed finding library", "Public property context", "Published scope and safety rules"],
    cadence: "Planned automatic property-context refreshes and quarterly technical review.",
    audiences: ["Homebuyers", "Inspectors", "Real-estate agents and transaction coordinators"],
    editorialUse: "A reusable explanation layer that helps buyers act on inspection findings without overdiagnosis.",
    guardrail: "The planner will explain and prioritize; it will not diagnose concealed conditions or replace a licensed inspection.",
  },
  {
    rank: 18,
    slug: "permit-rebate-incentive-navigator",
    title: "Austin Permit, Rebate and Incentive Navigator",
    shortTitle: "Permit and Rebate Navigator",
    metaTitle: "Austin Plumbing Permit & Rebate Navigator | Ironclad",
    metaDescription:
      "Find likely Austin-area plumbing permits, official applications, water and energy rebates, required documents and agency contacts by project.",
    category: "property-research",
    citationPotential: 2.5,
    embedPotential: 5,
    summary: "A jurisdiction-aware starting point for the paperwork, incentives and official next steps behind a home project.",
    signals: ["Likely permit paths", "Official applications and contacts", "Water and energy incentives"],
    sources: ["Local development-services guidance", "Austin Water programs", "Utility and government incentive pages"],
    cadence: "Planned official-page monitoring, change detection and human approval before rule updates.",
    audiences: ["Homeowners and remodelers", "Agents and inspectors", "Suppliers and property managers"],
    editorialUse: "A maintainable guide to the local paperwork and programs that are difficult for partners to track independently.",
    guardrail: "Answers will be labeled as guidance and linked to the controlling authority for confirmation.",
  },
  {
    rank: 21,
    slug: "seller-remodel-plumbing-planner",
    title: "Seller and Remodel Plumbing Planner",
    shortTitle: "Seller and Remodel Planner",
    metaTitle: "Austin Seller & Remodel Plumbing Planner | Ironclad",
    metaDescription:
      "Build a practical Austin plumbing project scope with rooms, fixtures, access, permitting, sequencing, contingency and broad budget bands.",
    category: "property-research",
    citationPotential: 2,
    embedPotential: 4.5,
    summary: "A project-scoping tool that helps sellers and remodelers prepare comparable, realistic plumbing requests.",
    signals: ["Room and fixture scope", "Access, relocation and permit factors", "Sequencing and broad budget bands"],
    sources: ["Austin Plumbing Cost Index", "Expert-reviewed scope rules", "Jurisdiction permit guidance"],
    cadence: "Planned cost-band updates with each reviewed index release.",
    audiences: ["Home sellers", "Real-estate agents", "Homeowners and remodeling teams"],
    editorialUse: "A consistent planning framework for discussing scope before requesting bids.",
    guardrail: "Generated ranges will be planning context, not an automated Ironclad quote or promise of final project cost.",
  },
];
