import type { DataDeskProduct } from "./types";

export const TOOL_AND_PARTNER_PRODUCTS: DataDeskProduct[] = [
  {
    rank: 13,
    slug: "austin-home-systems-triage",
    title: "Who Should I Call? Austin Home Systems Triage",
    shortTitle: "Home Systems Triage",
    metaTitle: "Who Should I Call? Austin Home Systems Triage",
    metaDescription:
      "Use a safety-reviewed Austin decision tree to identify the right home-service professional, utility, city service or emergency response.",
    category: "decision-tools",
    citationPotential: 3.5,
    embedPotential: 5,
    summary: "A deterministic decision tree that helps homeowners call the appropriate professional first.",
    signals: ["Problem location and visible symptoms", "Water, power and gas involvement", "Appropriate professional or emergency route"],
    sources: ["Expert-reviewed decision rules", "Official utility and emergency contacts", "Jurisdiction-specific service information"],
    cadence: "Planned central rule and contact updates with automated route tests.",
    audiences: ["Homeowners", "Realtors and title companies", "HOAs, inspectors and home-service partners"],
    editorialUse: "A neutral homeowner help desk partners can embed without asking their staff to diagnose problems.",
    guardrail: "Gas odor, carbon monoxide, fire, shock risk and rapidly spreading water will bypass ordinary troubleshooting.",
  },
  {
    rank: 14,
    slug: "tenant-plumbing-maintenance-triage",
    title: "Tenant Plumbing and Maintenance Triage",
    shortTitle: "Tenant Maintenance Triage",
    metaTitle: "Tenant Plumbing & Maintenance Triage | Ironclad",
    metaDescription:
      "Give Austin-area tenants a property-specific path for plumbing emergencies, routine tickets, shutoff steps, documentation and contacts.",
    category: "partner-operations",
    citationPotential: 3,
    embedPotential: 5,
    summary: "A property-manager-configured flow for recognizing emergencies and submitting more complete maintenance requests.",
    signals: ["Emergency versus routine route", "Property contacts and after-hours rules", "Safe documentation and shutoff steps"],
    sources: ["Ironclad-controlled safety logic", "Property-specific configurations", "Expert-reviewed issue flows"],
    cadence: "Planned centralized safety updates with partner-specific contact and property settings.",
    audiences: ["Property managers", "Multifamily operators", "Tenants and resident-service teams"],
    editorialUse: "An embeddable, partner-branded maintenance coordinator available around the clock.",
    guardrail: "Core emergency logic will remain controlled and tested even when partner branding and contact instructions vary.",
  },
  {
    rank: 16,
    slug: "austin-leak-cost-calculator",
    title: "Austin Leak Cost Calculator",
    shortTitle: "Leak Cost Calculator",
    metaTitle: "Austin Leak Cost Calculator: Gallons & Bill Impact",
    metaDescription:
      "Estimate gallons lost and Austin bill impact from a dripping faucet, running fixture or timed meter test with clearly stated rate assumptions.",
    category: "decision-tools",
    citationPotential: 2.5,
    embedPotential: 5,
    summary: "A local calculator converting drip counts or meter movement into flow, gallons and estimated Austin water cost.",
    signals: ["Drips or meter change", "Monthly and annual water loss", "Estimated local bill impact"],
    sources: ["Austin utility rate schedules", "Published flow conversions", "User-entered observations"],
    cadence: "Planned updates when official rate data or calculation guidance changes.",
    audiences: ["Homeowners", "HOAs and property managers", "Inspectors and real-estate agents"],
    editorialUse: "A simple, Austin-specific way to show residents what a small leak may cost.",
    guardrail: "Results will be estimates, with measurement method, rate version and assumptions visible beside the calculation.",
  },
  {
    rank: 17,
    slug: "water-heater-decision-lab",
    title: "Austin Water Heater Decision Lab",
    shortTitle: "Water Heater Decision Lab",
    metaTitle: "Austin Water Heater Decision Lab | Ironclad Plumbing",
    metaDescription:
      "Compare water-heater age, sizing, tank, tankless and heat-pump paths with Austin operating-cost, installation and incentive context.",
    category: "decision-tools",
    citationPotential: 2.5,
    embedPotential: 4.5,
    summary: "A structured replacement-planning tool for making water-heater decisions before a failure.",
    signals: ["Manufacturer and serial age context", "Household sizing", "Technology, operating-cost and incentive paths"],
    sources: ["Maintained manufacturer references", "Recognized efficiency methods", "Utility rates and official incentive programs"],
    cadence: "Planned monitoring of rates, incentives, specifications and manufacturer formats.",
    audiences: ["Homeowners", "Realtors and inspectors", "Energy and sustainability organizations"],
    editorialUse: "A local, documented comparison of common replacement paths and their practical tradeoffs.",
    guardrail: "Safety and eligibility changes will require human review, and results will not replace an on-site evaluation.",
  },
  {
    rank: 19,
    slug: "freeze-shutoff-plan-builder",
    title: "Freeze Preparation and Shutoff Plan Builder",
    shortTitle: "Freeze and Shutoff Plan Builder",
    metaTitle: "Austin Freeze & Water Shutoff Plan Builder | Ironclad",
    metaDescription:
      "Create a property-specific Austin freeze checklist and water-shutoff plan with valve photos, contacts, vulnerable fixtures and a QR card.",
    category: "decision-tools",
    citationPotential: 2,
    embedPotential: 5,
    summary: "A private, property-specific freeze and emergency plan residents can use before water starts entering a building.",
    signals: ["Shutoff location and photos", "Vulnerable fixtures and equipment", "Contacts, checklist and QR access"],
    sources: ["User-provided property details", "National Weather Service conditions", "Centrally reviewed safety instructions"],
    cadence: "Planned weather-triggered reminders and centrally versioned safety guidance.",
    audiences: ["Homeowners", "Property managers", "Realtors and HOAs"],
    editorialUse: "A practical preparedness tool for closings, resident programs and property operations.",
    guardrail: "Property details will be private by default, and instructions will distinguish known facts from user-entered labels.",
  },
  {
    rank: 20,
    slug: "pipe-material-pressure-flow-diagnostics",
    title: "Pipe Material, Pressure and Flow Diagnostic Suite",
    shortTitle: "Pipe, Pressure and Flow Suite",
    metaTitle: "Pipe Material, Pressure & Flow Guide | Ironclad",
    metaDescription:
      "Identify likely visible pipe materials and document pressure, fixture flow and symptom patterns with safe Austin homeowner next steps.",
    category: "decision-tools",
    citationPotential: 2,
    embedPotential: 4,
    summary: "A guided educational suite for describing visible plumbing materials, pressure readings and fixture-flow symptoms.",
    signals: ["Visible material characteristics", "Pressure-gauge readings", "Fixture-flow timing and symptom patterns"],
    sources: ["Field-verified examples", "Expert-reviewed identification rules", "User readings and observations"],
    cadence: "Planned periodic technical review and performance checks for any future image-assistance model.",
    audiences: ["Homeowners", "Inspectors and agents", "Home-service intake teams"],
    editorialUse: "A common vocabulary for describing plumbing observations without turning a photo into an inspection.",
    guardrail: "Low-confidence material results will stop at unable to identify; concealed materials will require inspection.",
  },
  {
    rank: 22,
    slug: "hoa-multifamily-water-risk",
    title: "HOA and Multifamily Water-Risk Toolkit",
    shortTitle: "HOA and Multifamily Toolkit",
    metaTitle: "HOA & Multifamily Water-Risk Toolkit | Ironclad",
    metaDescription:
      "Organize freeze readiness, shutoff plans, water alerts, leak incidents and resident reporting for Austin HOAs and multifamily portfolios.",
    category: "partner-operations",
    citationPotential: 1.5,
    embedPotential: 5,
    summary: "A private portfolio-readiness dashboard paired with a centrally maintained public resident center.",
    signals: ["Portfolio readiness and shutoff plans", "Active alerts and leak incidents", "Resident contacts and reporting forms"],
    sources: ["Ironclad Data Desk signals", "Property-specific configurations", "Owner-authorized utility data"],
    cadence: "Planned central weather updates with manager-maintained property contacts and incident details.",
    audiences: ["HOA boards", "Multifamily property managers", "Residents and portfolio operators"],
    editorialUse: "An operational water-risk center that partners can maintain across an entire portfolio.",
    guardrail: "Utility data will require owner authorization, and private property details will not appear in the public resident view.",
  },
  {
    rank: 23,
    slug: "austin-irrigation-water-budget",
    title: "Austin Irrigation, Water Budget and Restriction Widget",
    shortTitle: "Irrigation and Water Budget",
    metaTitle: "Austin Irrigation & Water Restriction Widget",
    metaDescription:
      "Combine Austin watering rules, assigned days, recent rainfall, irrigation-zone estimates, water cost and available rebates in one widget.",
    category: "partner-operations",
    citationPotential: 1.5,
    embedPotential: 4.5,
    summary: "A partner-configurable resident widget combining current watering rules, weather, estimated use and cost.",
    signals: ["Assigned watering days", "Recent rainfall and rain-delay context", "Zone use, cost and rebate estimates"],
    sources: ["Austin Water restrictions and programs", "Local weather observations", "User irrigation-zone inputs"],
    cadence: "Planned restriction and rebate monitoring with regular weather refreshes.",
    audiences: ["HOAs and neighborhood groups", "Property managers", "Landscapers and pool professionals"],
    editorialUse: "A compact, current resident reference that consolidates official rules and practical irrigation context.",
    guardrail: "The widget will link to official restrictions and will not override current utility instructions.",
  },
  {
    rank: 24,
    slug: "restaurant-commercial-water-drain-planner",
    title: "Restaurant and Commercial Water and Drain Planner",
    shortTitle: "Commercial Water and Drain Planner",
    metaTitle: "Austin Commercial Water & Drain Planner | Ironclad",
    metaDescription:
      "Plan Austin restaurant and commercial hot-water demand, fixtures, drain and grease risk, maintenance, shutoffs and water-use context.",
    category: "partner-operations",
    citationPotential: 1,
    embedPotential: 4,
    summary: "A business-continuity planner for documenting the water and drain systems a commercial operation depends on.",
    signals: ["Fixture and appliance inventory", "Hot-water and water-use estimates", "Drain risk, maintenance and shutoff plans"],
    sources: ["Business-provided configuration", "Expert-reviewed commercial checklists", "Utility rates and official programs"],
    cadence: "Planned centralized updates for rates, programs, checklists and maintenance guidance.",
    audiences: ["Restaurants and commercial tenants", "Property managers and landlords", "Associations, chambers and suppliers"],
    editorialUse: "A repeatable planning report intended to reduce water- and drain-related emergency closures.",
    guardrail: "Planning outputs will not replace code review, engineering, inspection or an on-site commercial plumbing assessment.",
  },
  {
    rank: 25,
    slug: "plumbing-troubleshooting-tools",
    title: "Austin Plumbing Troubleshooting Tools",
    shortTitle: "Plumbing Troubleshooting Tools",
    metaTitle: "Austin Plumbing Troubleshooting Tools | Ironclad",
    metaDescription:
      "Use focused Austin homeowner tools for running toilets, disposals, slow drains, no hot water, low pressure, sewer odors and urgency.",
    category: "decision-tools",
    citationPotential: 0.5,
    embedPotential: 3.5,
    summary: "Reusable first-question modules for common plumbing symptoms, urgency and safe next steps.",
    signals: ["Symptom-specific questions", "Safe immediate actions", "Urgency and appropriate next step"],
    sources: ["Expert-reviewed troubleshooting rules", "Emergency bypass rules", "Seasonal Austin maintenance guidance"],
    cadence: "Planned centralized rule updates with automated tests across every outcome.",
    audiences: ["Austin homeowners", "Property managers and HOAs", "Customer-service and home-service partners"],
    editorialUse: "Embeddable modules that answer the first questions a trained intake team asks.",
    guardrail: "The tools will stop at safe triage and will never encourage work involving gas, electrical or uncontrolled water hazards.",
  },
];
