import type { DataDeskProduct } from "./types";

export const LIVE_RISK_PRODUCTS: DataDeskProduct[] = [
  {
    rank: 1,
    slug: "austin-freeze-pipe-risk",
    title: "Austin Freeze Pipe Risk Index and Live Map",
    shortTitle: "Freeze Pipe Risk Index",
    metaTitle: "Austin Freeze Pipe Risk Index & Live Map | Ironclad",
    metaDescription:
      "Track Austin pipe-freeze risk, forecast thresholds, timing and neighborhood risk bands with a source-documented local index from Ironclad.",
    category: "live-risk",
    citationPotential: 5,
    embedPotential: 5,
    summary:
      "A current 0–100 index translating forecast conditions and local housing context into practical pipe-freeze risk bands.",
    signals: ["Lowest forecast temperature", "Hours below 32°F and 28°F", "Time to the dangerous period"],
    sources: ["National Weather Service forecasts and alerts", "Census housing-age estimates", "Anonymized Ironclad freeze-call patterns"],
    cadence: "Planned hourly updates during freeze conditions, with permanent event snapshots.",
    audiences: ["Austin newsrooms", "HOAs and property managers", "Homeowners and real-estate professionals"],
    editorialUse: "A ready-to-explain view of what a cold forecast may mean for Austin plumbing systems.",
    guardrail: "The index will estimate area conditions, not predict whether an individual property or pipe will freeze.",
  },
  {
    rank: 3,
    slug: "austin-plumbing-emergency-pulse",
    title: "Austin Plumbing Emergency Pulse",
    shortTitle: "Plumbing Emergency Pulse",
    metaTitle: "Austin Plumbing Emergency Pulse | Ironclad Data Desk",
    metaDescription:
      "Follow weekly Austin trends in leaks, burst pipes, sewer backups, drain clogs and water-heater failures using clearly separated local sources.",
    category: "live-risk",
    citationPotential: 5,
    embedPotential: 4,
    summary:
      "A recurring index showing whether common Austin plumbing emergencies are running above or below their normal levels.",
    signals: ["Week-over-week issue trends", "Weather correlation", "Geographic demand patterns"],
    sources: ["Anonymized Ironclad service demand", "Austin 311 public records", "National Weather Service observations"],
    cadence: "Planned nightly imports and a reviewed weekly public release.",
    audiences: ["Consumer reporters", "Property managers", "Restoration and home-service professionals"],
    editorialUse: "A recurring source for explaining when and why specific household plumbing problems are rising.",
    guardrail: "Ironclad demand and Austin 311 records will remain visibly separate and will not be presented as a citywide census.",
  },
  {
    rank: 6,
    slug: "austin-water-conditions",
    title: "Austin Water Conditions Dashboard",
    shortTitle: "Water Conditions Dashboard",
    metaTitle: "Austin Water Conditions Dashboard | Ironclad Data Desk",
    metaDescription:
      "See Austin drought status, watering restrictions, lake storage, rainfall, flood alerts and official water updates in one documented dashboard.",
    category: "live-risk",
    citationPotential: 4.5,
    embedPotential: 5,
    summary:
      "A single view of official water-supply, drought, rainfall and alert information with practical homeowner context.",
    signals: ["Highland Lakes storage", "Drought stage and restrictions", "Rainfall and active water alerts"],
    sources: ["LCRA Hydromet", "Austin Water public notices", "National Weather Service alerts"],
    cadence: "Planned frequent source polling, with human verification for emergency-status changes.",
    audiences: ["News and neighborhood sites", "HOAs and apartment communities", "Restaurants and real-estate professionals"],
    editorialUse: "A compact, source-linked summary of Austin's current water situation and homeowner implications.",
    guardrail: "The dashboard will identify its official sources and will not replace government emergency notifications.",
  },
  {
    rank: 7,
    slug: "austin-water-quality-hardness",
    title: "Austin Water Quality and Hardness Monitor",
    shortTitle: "Water Quality and Hardness",
    metaTitle: "Austin Water Quality & Hardness Monitor | Ironclad",
    metaDescription:
      "Explore published Austin water hardness, pH and dissolved-solids trends with practical context for scale, fixtures, heaters and appliances.",
    category: "live-risk",
    citationPotential: 4.5,
    embedPotential: 4,
    summary:
      "A carefully sourced monitor explaining what published Austin water measurements may mean for home plumbing and appliances.",
    signals: ["Hardness history", "pH and total dissolved solids", "Scale and appliance context"],
    sources: ["Austin Water monthly reports", "Austin Water quarterly reports", "Documented Ironclad field testing"],
    cadence: "Planned report monitoring and extraction, followed by validation and human approval.",
    audiences: ["Homeowners and buyers", "Inspectors and realtors", "Appliance, coffee and water-treatment professionals"],
    editorialUse: "A historical, plain-language reference for the plumbing effects of Austin's published water measurements.",
    guardrail: "Plumbing-impact context will remain separate from health claims and will never declare water safe or unsafe.",
  },
  {
    rank: 8,
    slug: "austin-flood-sewer-backflow-risk",
    title: "Austin Flood, Sewer and Backflow Risk Dashboard",
    shortTitle: "Flood, Sewer and Backflow Risk",
    metaTitle: "Austin Flood, Sewer & Backflow Risk Dashboard",
    metaDescription:
      "Connect Austin flood alerts, rainfall, stream levels and flood-zone context to sewer, backflow and post-flood plumbing precautions.",
    category: "live-risk",
    citationPotential: 4.5,
    embedPotential: 4,
    summary:
      "An event-focused dashboard connecting official flood conditions to the plumbing systems and precautions inside Austin homes.",
    signals: ["Active flood alerts", "Stream levels and recent rainfall", "Sewer and backflow precautions"],
    sources: ["National Weather Service alerts", "USGS and LCRA gauge data", "FEMA flood-hazard layers"],
    cadence: "Planned frequent updates during storms and archived pages after material events.",
    audiences: ["Local television and news sites", "Property managers and HOAs", "Restoration and insurance professionals"],
    editorialUse: "An actionable homeowner angle for storm coverage, supported by official alert and gauge data.",
    guardrail: "This product will not be presented as an insurance, engineering or official flood determination.",
  },
  {
    rank: 10,
    slug: "austin-storm-damage-survey",
    title: "Austin Freeze and Storm Damage Survey",
    shortTitle: "Storm Damage Survey",
    metaTitle: "Austin Freeze & Storm Damage Survey | Ironclad",
    metaDescription:
      "Follow transparent, event-specific Austin survey findings on household plumbing damage, repair-cost bands and time without service.",
    category: "live-risk",
    citationPotential: 4.5,
    embedPotential: 3,
    summary:
      "A moderated event survey designed to quantify how freezes and storms are affecting participating Austin households.",
    signals: ["Damage types and geography", "Repair-cost bands", "Time without service and time to help"],
    sources: ["Voluntary homeowner responses", "Separately labeled Ironclad records", "Separately labeled partner records"],
    cadence: "Planned activation at defined weather thresholds, with moderation before publication.",
    audiences: ["Local newsrooms", "HOAs and preparedness groups", "Homeowners and emergency planners"],
    editorialUse: "A timely, limitations-forward picture of reported household impact during a major local event.",
    guardrail: "Every release will show sample size, recruitment method and limitations; convenience samples will not be called representative.",
  },
];
